# Generated by Django 4.2.1 on 2023-05-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author_alter_recipe_cuisine_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
